### ISSUE TITLE
Install Xvfb to run Cypress E2E test in Gitpod

### ISSUE THREAD

**Issue by sinansonmez** [mattermost/mattermost-gitpod-config#9]
I am actively using Gitpod for my development for Mattermost. I wanted to write and run E2E for one of the task. When I try to run E2E tests I received the following error `Error: Your system is missing the dependency: Xvfb. Install Xvfb and run Cypress again.`

I was wondering if it is possible to do certain changes in this repo and make E2E running possible. I found [this issue](https://github.com/gitpod-io/gitpod/issues/1413) from gitpod which might be useful for first evaluation

Tagging @mickmister for visibility

**Comment by mickmister** [comment]
This may be a good opportunity to use the [custom Docker image](https://www.gitpod.io/docs/config-docker) feature of Gitpod to have dependencies like this installed upon workspace creation. We can optimize any workspace dependency setup here, as long as it's not dependent on the specific commit of the opening repository.

If we instead install the dependency in a script defined in `.gitpod.yml`, the dependency will need to be reinstalled every time the Gitpod workspace is resumed. This is because only changes to the `/workspace` folder are [persisted across prebuilds](https://www.gitpod.io/docs/prebuilds#workspace-directory-only).

@sinansonmez Are you interested in looking into this? I may have some time to look into this in the next coming days. Thanks for reporting this!

**Comment by sinansonmez** [comment]
@mickmister Thanks for providing your feedback on this. Unfortunately I am pretty busy nowadays and I won't have time to look at this. I would appreciate if you have time to work on this.
